### ISSUE TITLE
Simple WiFI Radio Compile Error

### ISSUE THREAD

**Issue by rodo2020** [schreibfaul1/ESP32-audioI2S#115]
Hello,
I get this error when compiling:
Simple_WiFi_Radio:257:74: error: no matching function for call to 'Audio::connecttohost(String&)'
Thanks for help.

**Comment by kamil-m-m** [comment]
Hi,
I'v got another error:
Simple_WiFi_Radio:65:18: error: variable or field 'draw_button' declared void
 void draw_button(btns b)
  Thanks for help.

**Comment by schreibfaul1** [comment]
Which IDE are you using? There are no problems with the Arduino IDE. Install the two libraries (audio and TFT) as a zip file and then create a new sketch. Then copy the content of 'Simple_WiFi_Radio.ino' into it, enter the WiFi SSID and PW, compile and upload it. And first set the partition scheme to 'Huge App' so that there is enough storage space.

**Comment by kamil-m-m** [comment]
I am using Arduino 1.8.13 and arduino-esp32 from https://github.com/espressif/arduino-esp32 (fresh installation).  
Libraries ESP32-audioI2S-master.zip and ESP32-TFT-Library-ILI9486-master.zip added.  Partition scheme set to "Huge App", SSID and password set too.
Now I'v got different error:
`C:\Users\mkm\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp: In constructor 'Audio::Audio()':
C:\Users\mkm\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:142:17: error: 'class WiFiClientSecure' has no member named 'setInsecure'
`
My board is LILYGO TTGO T-Koala Wrover-B.

**Comment by schreibfaul1** [comment]
It looks pretty good, now load the new ESP32 Arduino version into the boards manager and it will work for sure
![image](https://user-images.githubusercontent.com/26044260/110256539-bfd40880-7f99-11eb-98b2-17d24b07e71c.png)
