### ISSUE TITLE
Support for Seek in M4A files

### ISSUE THREAD

**Issue by phschoen** [schreibfaul1/ESP32-audioI2S#148]
I want to play a intermediate "info/warning" file while playing an M4A file. Therefore I switch from one to the other file and back after playback of the warning and seek to the previous position.

The problem here is that seek is not implemented for M4A files. 
I hacked already a expensive seek in the audio class but it is quite slow, since it has to read the full file again by skipping the actual play/delay code section in `playChunk()` by "seeking" or looping to `/dev/null` 

Is there the possibility to add a seek function for M4A in any kinds which is faster or an other way to switch from one file to the other and back without stopping the current one?

**Comment by schreibfaul1** [comment]
m4a files contain the AAC RAW format. In order to jump to a certain point in the file, the beginning of the next frame must be known so that the decoder can be positioned correctly. If you want to go back to a certain point in the file you have to remember the beginning of the last played frame.
I think there is a project for the Teensy in which several audio files can be played and mixed at the same time. Maybe that would be an alternative.
