### ISSUE TITLE
8bit DAC's of the ESP32

### ISSUE THREAD

**Issue by Fire-Dragon-TW** [schreibfaul1/ESP32-audioI2S#302]
How can I use 8bit DAC's of the ESP32

**Comment by Fire-Dragon-TW** [comment]
```C
#include "Audio.h"
#include "FS.h"
#include "SPIFFS.h"

#define I2S_DOUT      25
#define I2S_BCLK      27
#define I2S_LRC       26

Audio audio(true, I2S_DAC_CHANNEL_BOTH_EN);

void setup() {
    Serial.begin(115200);
    audio.setPinout(I2S_BCLK, I2S_LRC, I2S_DOUT);
    audio.setVolume(21);

    SPIFFS.begin();
    audio.connecttoFS(SPIFFS, "alert.mp3");
}

void loop()
{
    audio.loop();
}
```

**Comment by Fire-Dragon-TW** [comment]
![image](https://user-images.githubusercontent.com/101455800/166584638-f728b664-aee3-4269-a7db-8318d4436608.png)
![image](https://user-images.githubusercontent.com/101455800/166584691-13ede9a4-60de-4d0d-974a-d9f15d4dd159.png)

**Comment by Fire-Dragon-TW** [comment]
speaker is connected to GPIO 26 and GND

**Comment by ggssantos** [comment]
@Fire-Dragon-TW, this issue is not related to the library itself, it is a problem with the Espressif Arduino Core. The last version that the internal DAC works is the 2.0.0.
You need to open the board manager on your arduino IDE and downgrade the ESP32 to 2.0.0.

![image](https://user-images.githubusercontent.com/80653794/167295522-585ad55a-f2c1-4305-abba-6016bc574ad6.png)

The issue was discussed here: https://github.com/espressif/arduino-esp32/issues/5938

**Comment by jitendra1607** [comment]
@Fire-Dragon-TW @ggssantos 

I want to implement this library because it enables the internal DAC of ESP32 without any other hardware. Can you post a sample audio output recording, to judge the quality of simple speech voice? It would be really helpful to make a final decision. Thank you
