### ISSUE TITLE
Error opening audio when using SdFat

### ISSUE THREAD

**Issue by eggfly** [schreibfaul1/ESP32-audioI2S#426]
* https://github.com/schreibfaul1/ESP32-audioI2S/blob/fd64ffa05482040d80ec31ef82aed80af0c4db48/src/Audio.cpp#L2736

sizeof(char *) is always 1 @schreibfaul1 
This issue first introduced in commit: https://github.com/schreibfaul1/ESP32-audioI2S/commit/77fcdd3f70a9230e27875e1d3a5f81c2bd36d8b7

Maybe we can use  `m_chbufSize`?

**Comment by schreibfaul1** [comment]
Hello eggfly,
thank you for your contribution. The buffer is no longer generated statically, but dynamically depending on whether a PSRAM is available. So sizeof(m_chbuf) doesn't make sense anymore.
The reason I use sdfat is that the FS only supports ASCII, there is a bug when using UTF. There is an issue in the espressif/arduino-esp32 repo, the Espressif developers say the bug will be fixed with Arduino V2.0.6. Let's see.
