### ISSUE TITLE
 activate "SDFATFS_USED"    in Audio.h , It 's still  doesn't work 

### ISSUE THREAD

**Issue by monchai68** [schreibfaul1/ESP32-audioI2S#502]
activate "SDFATFS_USED" in Audio.h , It 's still doesn't work (Compile error)
https://github.com/schreibfaul1/ESP32-audioI2S/blob/master/examples/SdFat_example/SdFat_example.ino

**Comment by monchai68** [comment]
activate "SDFATFS_USED" in Audio.h , It 's still doesn't work
https://github.com/schreibfaul1/ESP32-audioI2S/blob/master/examples/SdFat_example/SdFat_example.ino

**Comment by schreibfaul1** [comment]
It can be. SDFAT is not really compatible with Espressif's FS.h. Previously, only file names with the extended ASCII character set could be created with it. This has changed since V.2.0.6. Chinese characters, for example, are now also allowed in the file names. So there is no reason to use SDFAT anymore.
